import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fine Spec Detailing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a>Fine Spec Detailing</a>
        </h1>
        <p className={styles.comingSoon}>
          Coming Soon
        </p>

        <p className={styles.description}>
          Coming Soon{' '}
          <code className={styles.code}>fine ass detailing</code>
        </p> 
 
        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Book Now</p>
          </a> 
        </div> 
      </main>

      <footer className={styles.footer}>
        <a
          target="_blank"
          rel="noopener noreferrer"
        >
          Fine Spec Detailing{' '}&copy; 2022
          {/* <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span> */}
        </a>
      </footer>
    </div>
  )
}
